version: '3'
services:
  mkdocs:
    image: squidfunk/mkdocs-material
    container_name: go-docs
    volumes:
      - .:/docs
    ports:
      - "8000:8000"
    command: serve --dev-addr=0.0.0.0:8000
